Repository KUIT-2/web-frontend, pull requests merged in 2023-11, with the labels that each got.

#56 [mission] week6
  week5/nangniya/todo/package-lock.json
  week5/nangniya/todo/package.json
  week5/nangniya/todo/public/index.html
  week5/nangniya/todo/src/App.js
  week5/nangniya/todo/src/Todo.css
  week5/nangniya/todo/src/Todo.js
  week5/nangniya/todo/src/db.json
  week5/nangniya/todo/src/index.js
  week6/nangniya/nangniya/.gitignore
  week6/nangniya/nangniya/README.md
  week6/nangniya/nangniya/package-lock.json
  week6/nangniya/nangniya/package.json
  week6/nangniya/nangniya/public/favicon.ico
  week6/nangniya/nangniya/public/index.html
  week6/nangniya/nangniya/public/logo192.png
  week6/nangniya/nangniya/public/logo512.png
  week6/nangniya/nangniya/public/manifest.json
  week6/nangniya/nangniya/public/robots.txt
  week6/nangniya/nangniya/src/App.js
  week6/nangniya/nangniya/src/FilterableProductTable.js
  week6/nangniya/nangniya/src/InputBar.js
  week6/nangniya/nangniya/src/ProductCategoryRow.js
  week6/nangniya/nangniya/src/ProductRow.js
  week6/nangniya/nangniya/src/ProductTable.js
  week6/nangniya/nangniya/src/SearchBar.js
  week6/nangniya/nangniya/src/index.js
Labels: 김나연

#57 [mission] week6
  .gitignore
  db.json
  package-lock.json
  week5/ho0010/package-lock.json
  week5/ho0010/package.json
  week5/ho0010/public/index.html
  week5/ho0010/src/App.js
  week5/ho0010/src/Todo.css
  week5/ho0010/src/Todo.js
  week5/ho0010/src/db.json
  week5/ho0010/src/index.js
  week6/ho0010/.gitignore
  week6/ho0010/README.md
  week6/ho0010/package-lock.json
  week6/ho0010/package.json
  week6/ho0010/public/favicon.ico
  week6/ho0010/public/index.html
  week6/ho0010/public/logo192.png
  week6/ho0010/public/logo512.png
  week6/ho0010/public/manifest.json
  week6/ho0010/public/robots.txt
  week6/ho0010/src/App.js
  week6/ho0010/src/FilterableProductTable.js
  week6/ho0010/src/InputBar.js
  week6/ho0010/src/ProductCategoryRow.js
  week6/ho0010/src/ProductRow.js
  week6/ho0010/src/ProductTable.js
  week6/ho0010/src/SearchBar.js
  week6/ho0010/src/index.js
Labels: 지호준

#60 [mission] week6
  week5/crohasang/package.json
  week5/crohasang/public/index.html
  week5/crohasang/src/App.js
  week5/crohasang/src/Todo.css
  week5/crohasang/src/Todo.js
  week5/crohasang/src/db.json
  week5/crohasang/src/index.js
  week6/crohasang/.gitignore
  week6/crohasang/README.md
  week6/crohasang/package-lock.json
  week6/crohasang/package.json
  week6/crohasang/public/favicon.ico
  week6/crohasang/public/index.html
  week6/crohasang/public/logo192.png
  week6/crohasang/public/logo512.png
  week6/crohasang/public/manifest.json
  week6/crohasang/public/robots.txt
  week6/crohasang/src/App.js
  week6/crohasang/src/FilterableProductTable.js
  week6/crohasang/src/InputBar.js
  week6/crohasang/src/ProductCategoryRow.js
  week6/crohasang/src/ProductRow.js
  week6/crohasang/src/ProductTable.js
  week6/crohasang/src/SearchBar.js
  week6/crohasang/src/index.js
Labels: 조하상

#66 [mission] week6
  week4/algoORgoal/.gitignore
  week5/algoORgoal/todo/package.json
  week5/algoORgoal/todo/public/index.html
  week5/algoORgoal/todo/src/App.js
  week5/algoORgoal/todo/src/Todo.css
  week5/algoORgoal/todo/src/Todo.js
  week5/algoORgoal/todo/src/db.json
  week5/algoORgoal/todo/src/index.js
  week5/algoORgoal/todo/yarn.lock
  week6/algoorgoal/.gitignore
  week6/algoorgoal/README.md
  week6/algoorgoal/package.json
  week6/algoorgoal/public/index.html
  week6/algoorgoal/public/robots.txt
  week6/algoorgoal/src/App.tsx
  week6/algoorgoal/src/FilterableProductTable.tsx
  week6/algoorgoal/src/InputBar.tsx
  week6/algoorgoal/src/ProductCategoryRow.tsx
  week6/algoorgoal/src/ProductRow.tsx
  week6/algoorgoal/src/ProductTable.tsx
  week6/algoorgoal/src/SearchBar.tsx
  week6/algoorgoal/src/index.tsx
  week6/algoorgoal/src/react-app-env.d.ts
  week6/algoorgoal/tsconfig.json
  week6/algoorgoal/yarn.lock
Labels: 김별찬

#67 [mission] week6
  week6/parkcoool/my-react-app/.gitignore
  week6/parkcoool/my-react-app/README.md
  week6/parkcoool/my-react-app/package-lock.json
  week6/parkcoool/my-react-app/package.json
  week6/parkcoool/my-react-app/public/index.html
  week6/parkcoool/my-react-app/src/App.jsx
  week6/parkcoool/my-react-app/src/FilterableProductTable.jsx
  week6/parkcoool/my-react-app/src/NewProductForm.jsx
  week6/parkcoool/my-react-app/src/ProductCategoryRow.jsx
  week6/parkcoool/my-react-app/src/ProductRow.jsx
  week6/parkcoool/my-react-app/src/ProductTable.jsx
  week6/parkcoool/my-react-app/src/ProductTableContainer.jsx
  week6/parkcoool/my-react-app/src/SearchBar.jsx
  week6/parkcoool/my-react-app/src/index.css
  week6/parkcoool/my-react-app/src/index.js
Labels: 박시원

#65 [mission] week6
  week6/unique0902/.gitignore
  week6/unique0902/README.md
  week6/unique0902/package-lock.json
  week6/unique0902/package.json
  week6/unique0902/public/favicon.ico
  week6/unique0902/public/index.html
  week6/unique0902/public/logo192.png
  week6/unique0902/public/logo512.png
  week6/unique0902/public/manifest.json
  week6/unique0902/public/robots.txt
  week6/unique0902/src/App.css
  week6/unique0902/src/App.js
  week6/unique0902/src/FilterableProductTable.jsx
  week6/unique0902/src/InputBar.jsx
  week6/unique0902/src/ProductCategoryRow.jsx
  week6/unique0902/src/ProductRow.jsx
  week6/unique0902/src/ProductTable.jsx
  week6/unique0902/src/SearchBar.jsx
  week6/unique0902/src/index.css
  week6/unique0902/src/index.js
Labels: 김태현

#62 [mission] week6
  week5/hyunn522/todo/package-lock.json
  week5/hyunn522/todo/package.json
  week5/hyunn522/todo/public/index.html
  week5/hyunn522/todo/src/App.js
  week5/hyunn522/todo/src/Todo.css
  week5/hyunn522/todo/src/Todo.js
  week5/hyunn522/todo/src/db.json
  week5/hyunn522/todo/src/index.js
  week6/hyunn522/.gitignore
  week6/hyunn522/README.md
  week6/hyunn522/package-lock.json
  week6/hyunn522/package.json
  week6/hyunn522/public/favicon.ico
  week6/hyunn522/public/index.html
  week6/hyunn522/public/logo192.png
  week6/hyunn522/public/logo512.png
  week6/hyunn522/public/manifest.json
  week6/hyunn522/public/robots.txt
  week6/hyunn522/src/App.js
  week6/hyunn522/src/FilterableProductTable.js
  week6/hyunn522/src/InputBar.js
  week6/hyunn522/src/ProductCategoryRow.js
  week6/hyunn522/src/ProductRow.js
  week6/hyunn522/src/ProductTable.js
  week6/hyunn522/src/SearchBar.js
  week6/hyunn522/src/index.js
Labels: 정서현

#69 [mission] week6
  week6/somin-jeong/.gitignore
  week6/somin-jeong/README.md
  week6/somin-jeong/package-lock.json
  week6/somin-jeong/package.json
  week6/somin-jeong/public/favicon.ico
  week6/somin-jeong/public/index.html
  week6/somin-jeong/public/logo192.png
  week6/somin-jeong/public/logo512.png
  week6/somin-jeong/public/manifest.json
  week6/somin-jeong/public/robots.txt
  week6/somin-jeong/src/App.js
  week6/somin-jeong/src/FilterableProductTable.js
  week6/somin-jeong/src/InputBar.js
  week6/somin-jeong/src/ProductCategoryRow.js
  week6/somin-jeong/src/ProductRow.js
  week6/somin-jeong/src/ProductTable.js
  week6/somin-jeong/src/SearchBar.js
  week6/somin-jeong/src/index.js
Labels: 정소민

#63 [mission] week6
  week5/ssilver01/todo/.gitignore
  week5/ssilver01/todo/README.md
  week5/ssilver01/todo/package-lock.json
  week5/ssilver01/todo/package.json
  week5/ssilver01/todo/public/index.html
  week5/ssilver01/todo/src/App.js
  week5/ssilver01/todo/src/Todo.css
  week5/ssilver01/todo/src/Todo.js
  week5/ssilver01/todo/src/db.json
  week5/ssilver01/todo/src/index.js
  week6/ssilver01/.gitignore
  week6/ssilver01/README.md
  week6/ssilver01/package-lock.json
  week6/ssilver01/package.json
  week6/ssilver01/public/favicon.ico
  week6/ssilver01/public/index.html
  week6/ssilver01/public/logo192.png
  week6/ssilver01/public/logo512.png
  week6/ssilver01/public/manifest.json
  week6/ssilver01/public/robots.txt
  week6/ssilver01/src/App.js
  week6/ssilver01/src/FilterableProductTable.js
  week6/ssilver01/src/InputBar.js
  week6/ssilver01/src/ProductCategoryRow.js
  week6/ssilver01/src/ProductRow.js
  week6/ssilver01/src/ProductTable.js
  week6/ssilver01/src/SearchBar.js
  week6/ssilver01/src/index.js
Labels: 정소은

#71 [mission] week7
  week7/nangniya/.gitignore
  week7/nangniya/README.md
  week7/nangniya/package-lock.json
  week7/nangniya/package.json
  week7/nangniya/public/favicon.ico
  week7/nangniya/public/index.html
  week7/nangniya/public/logo192.png
  week7/nangniya/public/logo512.png
  week7/nangniya/public/manifest.json
  week7/nangniya/public/robots.txt
  week7/nangniya/src/App.js
  week7/nangniya/src/components/Button.jsx
  week7/nangniya/src/components/FilterableProductTable.js
  week7/nangniya/src/components/GlobalStyle.jsx
  week7/nangniya/src/components/Input.jsx
  week7/nangniya/src/components/ProductCategoryRow.js
  week7/nangniya/src/components/ProductForm.jsx
  week7/nangniya/src/components/ProductForm.styles.jsx
  week7/nangniya/src/components/ProductRow.js
  week7/nangniya/src/components/ProductRow.styles.jsx
  week7/nangniya/src/components/ProductTable.js
  week7/nangniya/src/components/SearchBar.js
  week7/nangniya/src/components/SearchBar.styles.jsx
  week7/nangniya/src/index.js
  week7/nangniya/src/routes/Home.jsx
  week7/nangniya/src/routes/Products.jsx
  week7/nangniya/src/routes/Router.jsx
Labels: 김나연

#72 [mission] week7
  week7/crohasang/.gitignore
  week7/crohasang/README.md
  week7/crohasang/package-lock.json
  week7/crohasang/package.json
  week7/crohasang/public/favicon.ico
  week7/crohasang/public/index.html
  week7/crohasang/public/logo192.png
  week7/crohasang/public/logo512.png
  week7/crohasang/public/manifest.json
  week7/crohasang/public/robots.txt
  week7/crohasang/src/App.jsx
  week7/crohasang/src/components/FilterableProductTable.jsx
  week7/crohasang/src/components/GlobalStyles.jsx
  week7/crohasang/src/components/Input.jsx
  week7/crohasang/src/components/ProductForm.jsx
  week7/crohasang/src/components/ProductForm.styles.jsx
  week7/crohasang/src/components/ProductRow.jsx
  week7/crohasang/src/components/ProductRow.styles.jsx
  week7/crohasang/src/components/ProductTable.jsx
  week7/crohasang/src/components/SearchBar.jsx
  week7/crohasang/src/components/SearchBar.styles.jsx
  week7/crohasang/src/index.js
  week7/crohasang/src/routes/Home.jsx
  week7/crohasang/src/routes/Home.styles.jsx
  week7/crohasang/src/routes/Products.jsx
  week7/crohasang/src/routes/Router.jsx
Labels: 조하상

#73 [mission]week7
  package-lock.json
  package.json
  week7/hyunn522/.gitignore
  week7/hyunn522/README.md
  week7/hyunn522/package-lock.json
  week7/hyunn522/package.json
  week7/hyunn522/public/favicon.ico
  week7/hyunn522/public/index.html
  week7/hyunn522/public/logo192.png
  week7/hyunn522/public/logo512.png
  week7/hyunn522/public/manifest.json
  week7/hyunn522/public/robots.txt
  week7/hyunn522/src/App.jsx
  week7/hyunn522/src/components/FilterableProductTable.jsx
  week7/hyunn522/src/components/GlobalStyle.jsx
  week7/hyunn522/src/components/Input.jsx
  week7/hyunn522/src/components/ProductForm.jsx
  week7/hyunn522/src/components/ProductForm.styles.jsx
  week7/hyunn522/src/components/ProductRow.jsx
  week7/hyunn522/src/components/ProductRow.styles.jsx
  week7/hyunn522/src/components/ProductTable.jsx
  week7/hyunn522/src/components/SearchBar.jsx
  week7/hyunn522/src/components/SearchBar.styles.jsx
  week7/hyunn522/src/index.js
  week7/hyunn522/src/routes/Home.jsx
  week7/hyunn522/src/routes/Products.jsx
  week7/hyunn522/src/routes/Router.jsx
Labels: 정서현

#74 [mission] week7
  week6/cylee1111/src/ProductTable.js
  week7/cylee1111/.gitignore
  week7/cylee1111/README.md
  week7/cylee1111/package-lock.json
  week7/cylee1111/package.json
  week7/cylee1111/public/favicon.ico
  week7/cylee1111/public/index.html
  week7/cylee1111/public/logo192.png
  week7/cylee1111/public/logo512.png
  week7/cylee1111/public/manifest.json
  week7/cylee1111/public/robots.txt
  week7/cylee1111/src/App.jsx
  week7/cylee1111/src/components/FilterableProductTable.jsx
  week7/cylee1111/src/components/GlobalStyle.jsx
  week7/cylee1111/src/components/Input.jsx
  week7/cylee1111/src/components/ProductCategoryRow.jsx
  week7/cylee1111/src/components/ProductForm.jsx
  week7/cylee1111/src/components/ProductForm.styles.jsx
  week7/cylee1111/src/components/ProductRow.jsx
  week7/cylee1111/src/components/ProductTable.jsx
  week7/cylee1111/src/components/SearchBar.jsx
  week7/cylee1111/src/components/SearchBar.styles.jsx
  week7/cylee1111/src/index.js
  week7/cylee1111/src/routes/Home.jsx
  week7/cylee1111/src/routes/Products.jsx
  week7/cylee1111/src/routes/Router.jsx
Labels: 이찬양

#75 [mission] week7
  week7/somin-jeong/.gitignore
  week7/somin-jeong/README.md
  week7/somin-jeong/package-lock.json
  week7/somin-jeong/package.json
  week7/somin-jeong/public/favicon.ico
  week7/somin-jeong/public/index.html
  week7/somin-jeong/public/logo192.png
  week7/somin-jeong/public/logo512.png
  week7/somin-jeong/public/manifest.json
  week7/somin-jeong/public/robots.txt
  week7/somin-jeong/src/App.jsx
  week7/somin-jeong/src/components/FilterableProductTable.jsx
  week7/somin-jeong/src/components/GlobalStyle.jsx
  week7/somin-jeong/src/components/Input.jsx
  week7/somin-jeong/src/components/ProductForm.jsx
  week7/somin-jeong/src/components/ProductForm.styles.jsx
  week7/somin-jeong/src/components/ProductRow.jsx
  week7/somin-jeong/src/components/ProductRow.style.jsx
  week7/somin-jeong/src/components/ProductTable.jsx
  week7/somin-jeong/src/components/ProductTable.styles.jsx
  week7/somin-jeong/src/components/SearchBar.jsx
  week7/somin-jeong/src/components/SearchBar.styles.jsx
  week7/somin-jeong/src/index.js
  week7/somin-jeong/src/routes/Home.jsx
  week7/somin-jeong/src/routes/Products.jsx
  week7/somin-jeong/src/routes/Router.jsx
Labels: 정소민

#76 [mission] week7
  week7/ssilver01/.gitignore
  week7/ssilver01/README.md
  week7/ssilver01/package-lock.json
  week7/ssilver01/package.json
  week7/ssilver01/public/favicon.ico
  week7/ssilver01/public/index.html
  week7/ssilver01/public/logo192.png
  week7/ssilver01/public/logo512.png
  week7/ssilver01/public/manifest.json
  week7/ssilver01/public/robots.txt
  week7/ssilver01/src/App.jsx
  week7/ssilver01/src/components/FilterableProductTable.jsx
  week7/ssilver01/src/components/FilterableProductTable.styles.jsx
  week7/ssilver01/src/components/GlobalStyle.jsx
  week7/ssilver01/src/components/Input.jsx
  week7/ssilver01/src/components/ProductForm.jsx
  week7/ssilver01/src/components/ProductForm.styles.jsx
  week7/ssilver01/src/components/ProductRow.jsx
  week7/ssilver01/src/components/ProductTable.jsx
  week7/ssilver01/src/components/SearchBar.jsx
  week7/ssilver01/src/components/SearchBar.styles.jsx
  week7/ssilver01/src/index.js
  week7/ssilver01/src/routes/Home.jsx
  week7/ssilver01/src/routes/Products.jsx
  week7/ssilver01/src/routes/Router.jsx
Labels: 정소은

#81 [mission] week7
  week7/unique0902/.gitignore
  week7/unique0902/README.md
  week7/unique0902/package-lock.json
  week7/unique0902/package.json
  week7/unique0902/public/favicon.ico
  week7/unique0902/public/index.html
  week7/unique0902/public/logo192.png
  week7/unique0902/public/logo512.png
  week7/unique0902/public/manifest.json
  week7/unique0902/public/robots.txt
  week7/unique0902/src/App.js
  week7/unique0902/src/components/Button/IconButton/IconButton.jsx
  week7/unique0902/src/components/Button/IconButton/IconButton.module.css
  week7/unique0902/src/components/Button/TextButton/TextButton.jsx
  week7/unique0902/src/components/Button/TextButton/TextButton.module.css
  week7/unique0902/src/components/Product/FilterableProductTable/FilterableProductTable.jsx
  week7/unique0902/src/components/Product/FilterableProductTable/FilterableProductTable.module.css
  week7/unique0902/src/components/Product/ProductForm/AddProductForm.jsx
  week7/unique0902/src/components/Product/ProductForm/EditProductForm.jsx
  week7/unique0902/src/components/Product/ProductForm/ProductForm.jsx
  week7/unique0902/src/components/Product/ProductForm/ProductForm.module.css
  week7/unique0902/src/components/Product/ProductRow/ProductRow.jsx
  week7/unique0902/src/components/Product/ProductRow/ProductRow.module.css
  week7/unique0902/src/components/Product/ProductSearchForm/ProductSearchForm.jsx
  week7/unique0902/src/components/Product/ProductSearchForm/ProductSearchForm.module.css
  week7/unique0902/src/components/Product/ProductTable/ProductTable.jsx
  week7/unique0902/src/components/Product/ProductTable/ProductTable.module.css
  week7/unique0902/src/components/Product/ProductTableHead/ProductTableHead.jsx
  week7/unique0902/src/components/Product/ProductTableHead/ProductTableHead.module.css
  week7/unique0902/src/components/SearchBar/SearchBar.jsx
  week7/unique0902/src/components/SearchBar/SearchBar.module.css
  week7/unique0902/src/hooks/product-reducer.js
  week7/unique0902/src/index.css
  week7/unique0902/src/index.js
  week7/unique0902/src/routes/ErrorPage.jsx
  week7/unique0902/src/routes/Home.jsx
  week7/unique0902/src/routes/Products.jsx
  week7/unique0902/src/routes/Router.jsx
Labels: 김태현
